services:
  mysqldb:
    image: 'mysql:latest'

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_info

    container_name: "mysqldb"
    networks:
      - my-network
    # helth check will check the container is up or not
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
     
      timeout: 20s
      retries: 10
      # start_period: 30s
    
  mypythonapp:
    build: ./
    container_name: mypyapp
    networks:
      - my-network
    depends_on:
       mysqldb:
          condition: service_healthy
   
    # intractive mode
    stdin_open: true 
    tty: true
    
networks:
  my-network:
      







